import pandas as pd
from sqlalchemy.orm import Session
from models import ResidentProfile
from datetime import datetime
import io

def clean_str(val):
    """
    Converts 'nan', 'None', or empty values to an empty string.
    """
    if pd.isna(val) or val is None:
        return ""
    
    text = str(val).strip()
    
    # Check for literal "nan" or "None" strings generated by pandas
    if text.lower() in ['nan', 'none', 'null']:
        return ""
        
    return text

def parse_date(date_val):
    if pd.isna(date_val) or str(date_val).strip() == "":
        return None
    
    # Handle Excel Timestamps
    if isinstance(date_val, (pd.Timestamp, datetime)):
        return date_val.date()

    text_val = str(date_val).strip()
    if text_val.lower() in ['nan', 'none']:
        return None
    
    # Try multiple date formats
    for fmt in ('%m/%d/%Y', '%Y-%m-%d', '%d-%b-%y', '%m-%d-%Y', '%Y/%m/%d'):
        try:
            return datetime.strptime(text_val, fmt).date()
        except ValueError:
            continue
    return None

def get_sectors(row):
    active_sectors = []
    
    # Scan these specific columns for any value
    possible_sectors = [
        'FARMER', 'FISHERFOLK', 'FISHERMAN/BANCA OWNER', 'TODA', 
        'BRGY BNS/BHW', 'BRGY TANOD', 'BRGY OFFICIAL', 'LGU EMPLOYEE', 
        'INDIGENOUS PEOPLE', 'PWD', 'OFW', 'STUDENT', 
        'SENIOR CITIZEN', 'LIFEGUARD', 'SOLO PARENT'
    ]

    for sector in possible_sectors:
        val = row.get(sector)
        # Check using our clean_str helper
        if clean_str(val) != "":
            active_sectors.append(sector)

    # Handle OTHERS
    other_val = clean_str(row.get('OTHERS'))
    other_details = None
    
    if other_val != "":
        active_sectors.append("Others")
        if len(other_val) > 1:
            other_details = other_val

    summary = ", ".join(active_sectors) if active_sectors else "None"
    return summary, other_details

def process_excel_import(file_content, db: Session):
    # 1. Read File
    try:
        df = pd.read_excel(file_content, dtype=str, engine='openpyxl')
    except Exception as e_xlsx:
        file_content.seek(0)
        try:
            df = pd.read_csv(file_content, dtype=str, encoding='cp1252')
        except Exception as e_csv:
            return {"added": 0, "errors": [f"Could not read file. Error: {str(e_xlsx)}"]}

    # 2. Normalize Headers
    df.columns = df.columns.str.strip().str.upper()
    
    success_count = 0
    errors = []

    # 3. Iterate Rows
    for index, row in df.iterrows():
        try:
            # Required Field Check
            lname = clean_str(row.get('LAST NAME'))
            if not lname:
                continue

            # --- PARSE PERSONAL ---
            fname = clean_str(row.get('FIRST NAME'))
            mname = clean_str(row.get('MIDDLE NAME'))
            ext   = clean_str(row.get('EXT NAME'))
            
            # --- PARSE SPOUSE ---
            spouse_lname  = clean_str(row.get('LAST NAME.1'))
            spouse_fname  = clean_str(row.get('FIRST NAME.1'))
            spouse_mname  = clean_str(row.get('MIDDLE NAME.1'))
            spouse_ext    = clean_str(row.get('EXT NAME.1'))

            # --- PARSE DATE ---
            birthdate = parse_date(row.get('BIRTHDATE'))

            # --- PARSE SECTORS ---
            sector_summary_str, other_details_str = get_sectors(row)

            # --- CREATE OBJECT ---
            resident = ResidentProfile(
                last_name=lname,
                first_name=fname,
                middle_name=mname,
                ext_name=ext,
                
                # Address (Cleaned)
                house_no=clean_str(row.get('HOUSE NO. / STREET')),
                purok=clean_str(row.get('PUROK/SITIO')),
                barangay=clean_str(row.get('BARANGAY')),
                
                # Personal (Cleaned)
                sex=clean_str(row.get('SEX')),
                birthdate=birthdate,
                civil_status=clean_str(row.get('CIVIL STATUS')),
                religion=clean_str(row.get('RELIGION')),
                occupation=clean_str(row.get('OCCUPATION')),
                contact_no=clean_str(row.get('CONTACT')),
                precinct_no=clean_str(row.get('PRECINT NO')),
                
                # Sectors
                sector_summary=sector_summary_str,
                other_sector_details=other_details_str,
                
                # Spouse
                spouse_last_name=spouse_lname,
                spouse_first_name=spouse_fname,
                spouse_middle_name=spouse_mname,
                spouse_ext_name=spouse_ext,
            )
            
            db.add(resident)
            success_count += 1
            
        except Exception as e:
            errors.append(f"Row {index + 2} Skipped: {str(e)}")

    # 4. SAFE COMMIT
    try:
        db.commit()
    except Exception as e:
        db.rollback()
        return {"added": 0, "errors": [f"Database Save Error: {str(e)}"]}
    
    return {"added": success_count, "errors": errors}